# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Deploy Python App to Azure Web App - AppRecom

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write    # indispensable pour Azure login via OIDC
      contents: read
    steps:
      # 1️⃣ Récupérer le repo
      - uses: actions/checkout@v3

      # 2️⃣ Configurer Python
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # 3️⃣ Installer les dépendances depuis requirements.txt
      - name: Install dependencies
        run: pip install --upgrade pip
      - run: pip install -r requirements.txt

      # 4️⃣ Déployer sur Azure App Service
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_E4D7FCF738364690913B509D91B04D9A }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_5E480B1712A740449A25BA5139B2842D }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_D74B060BC6644532B87898F07F2537CD }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'AppRecom'
          slot-name: 'Production'
          package: '.'


          

